# Generated by Django 3.0.3 on 2020-04-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pincodemodel',
            old_name='PinCode',
            new_name='pincode',
        ),
    ]
